import { defineConfig } from '@hey-api/openapi-ts';

// Generates the TypeScript client from contract/openapi.yaml.
// Never edit the output in src/generated by hand — see README.md.
export default defineConfig({
  input: '../../contract/openapi.yaml',
  output: 'src/generated',
  plugins: ['@hey-api/client-fetch', '@hey-api/typescript', '@hey-api/sdk'],
});
