"""initial schema

Revision ID: 762f23e14ca7
Revises:
Create Date: 2026-09-25 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '762f23e14ca7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identity_audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('correlation_id', sa.String(length=200), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identity_audit_logs_entity_id'), 'identity_audit_logs', ['entity_id'], unique=False)
    op.create_table('identity_roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('identity_users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identity_users_deleted_at'), 'identity_users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_identity_users_email'), 'identity_users', ['email'], unique=True)
    op.create_table('shared_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=200), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.String(length=200), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shared_jobs_owner_id'), 'shared_jobs', ['owner_id'], unique=False)
    op.create_index(op.f('ix_shared_jobs_state'), 'shared_jobs', ['state'], unique=False)
    op.create_table('identity_refresh_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_token_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['identity_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identity_refresh_tokens_token_hash'), 'identity_refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_identity_refresh_tokens_user_id'), 'identity_refresh_tokens', ['user_id'], unique=False)
    op.create_table('identity_user_roles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['identity_roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['identity_users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('identity_user_roles')
    op.drop_index(op.f('ix_identity_refresh_tokens_user_id'), table_name='identity_refresh_tokens')
    op.drop_index(op.f('ix_identity_refresh_tokens_token_hash'), table_name='identity_refresh_tokens')
    op.drop_table('identity_refresh_tokens')
    op.drop_index(op.f('ix_shared_jobs_state'), table_name='shared_jobs')
    op.drop_index(op.f('ix_shared_jobs_owner_id'), table_name='shared_jobs')
    op.drop_table('shared_jobs')
    op.drop_index(op.f('ix_identity_users_email'), table_name='identity_users')
    op.drop_index(op.f('ix_identity_users_deleted_at'), table_name='identity_users')
    op.drop_table('identity_users')
    op.drop_table('identity_roles')
    op.drop_index(op.f('ix_identity_audit_logs_entity_id'), table_name='identity_audit_logs')
    op.drop_table('identity_audit_logs')
    # ### end Alembic commands ###
